# Site settings
title: Microdust
header-img: "img/autumn2.jpg"
tagline: "吉光片羽"  
description: "以梦为马 诗酒趁年华"  
baseurl: ""
url: "sugardream.github.io"  
#url: "sugardream.github.io"

# About/contact
owner: 
  name: "sugardream"
  email: sclink69@gmail.com
  bio: "以梦为马 诗酒趁年华"

# Data
gavatar: http://ww1.sinaimg.cn/mw690/0065PbKCgw1fa13aqk26uj30hr0hsq3r.jpg
favicon: img/damotouicon.ico

douban_username: 
twitter_username:   
github_username:店小二   
facebook_username:   
weibo_username:  
zhihu_username:   

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Azeril"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 店小二
  disqus :
      short_name : 店小二

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation